services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: mongo
    healthcheck:
      test: [ "CMD", "mongod"]
      interval: 1s
      retries: 3
      start_period: 5s
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
