services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: mongo
    healthcheck:
      test: ["mongod"]
      interval: 1s
      retries: 1
      start_period: 1s
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
